update aws/assume-role to generate before hook to assume role

diff --git a/aws/assume-role/mint-leaf.yml b/aws/assume-role/mint-leaf.yml
--- a/aws/assume-role/mint-leaf.yml
+++ b/aws/assume-role/mint-leaf.yml
@@ -1,13 +1,10 @@
 name: aws/assume-role
-version: 1.1.4
+version: 2.0.0
 description: Assume an AWS role
 source_code_url: https://github.com/rwx-research/mint-leaves/tree/main/aws/assume-role
 issue_tracker_url: https://github.com/rwx-research/mint-leaves/issues
 
 parameters:
-  oidc-token:
-    description: "The OIDC token that will be exchanged for temporary credentials (e.g. vaults.your-vault.oidc.your-token). If not set, the AWS CLI must already be configured with credentials that can assume the role specified."
-    required: false
   region:
     description: "The AWS region (e.g. us-east-2)."
     required: true
@@ -26,58 +23,47 @@ parameters:
   source-profile-name:
     description: "The profile used to assume the chained role (not used when an OIDC token is provided)."
     default: "default"
+  oidc-token-env-var:
+    description: "The environment variable that contains the OIDC token."
+    default: "AWS_OIDC_TOKEN"
 
 tasks:
-  - key: assume-role
+  - key: produce-assume-role-hooks
     run: |
       set -ueo pipefail
 
-      cat << EOF > $(mktemp "$MINT_WARNINGS/warning-XXXX")
-      This leaf is being deprecated. Please upgrade to \`2.0.0\` or later. See [upgrade instructions](https://cloud.rwx.com/leaves/aws/assume-role) for more detail.
-      EOF
+      BEFORE_HOOK_TEMPLATE="$MINT_LEAF_PATH/before-hook.template.txt"
 
-      if ! command -v aws &> /dev/null; then
-        cat << EOF > $(mktemp "$MINT_ERRORS/error-XXXX")
-      The AWS CLI must be installed. To install it, you can use the \`aws/install-cli\` leaf.
-      EOF
+      if [[ ! -f $BEFORE_HOOK_TEMPLATE ]]; then
+        echo "Template file '$BEFORE_HOOK_TEMPLATE' not found."
         exit 1
       fi
 
-      role_session_name="${{ params.role-session-name }}"
-      if [[ -z "$role_session_name" ]]; then
-        role_session_name="assumed-role-for-mint-run-${{ run.id }}"
-      fi
+      BEFORE_HOOK="$MINT_HOOKS_BEFORE_TASK/aws-assume-role--assume-${{ params.profile-name }}.sh"
+      AFTER_HOOK="$MINT_HOOKS_AFTER_TASK/aws-assume-role--assume-${{ params.profile-name }}.sh"
 
-      if [[ -z "${{ params.oidc-token }}" ]]; then
-        sts_result=$(
-          aws sts assume-role \
-          --role-arn "${{ params.role-to-assume }}" \
-          --role-session-name "$role_session_name" \
-          --profile "${{ params.source-profile-name }}" \
-          --duration-seconds ${{ params.role-duration-seconds }} \
-          --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
-          --output text
-        )
-        export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" $sts_result)
-      else
-        sts_result=$(
-          aws sts assume-role-with-web-identity \
-          --role-arn "${{ params.role-to-assume }}" \
-          --role-session-name "$role_session_name" \
-          --web-identity-token "${{ params.oidc-token }}" \
-          --duration-seconds ${{ params.role-duration-seconds }} \
-          --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
-          --output text
-        )
-        export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" $sts_result)
-      fi
+      awk \
+        -v REGION="${{ params.region }}" \
+        -v ROLE_TO_ASSUME="${{ params.role-to-assume }}" \
+        -v ROLE_DURATION_SECONDS="${{ params.role-duration-seconds }}" \
+        -v ROLE_SESSION_NAME="${{ params.role-session-name }}" \
+        -v PROFILE_NAME="${{ params.profile-name }}" \
+        -v OIDC_TOKEN_ENV_VAR="${{ params.oidc-token-env-var }}" \
+      '{
+          gsub("%{{REGION}}", REGION);
+          gsub("%{{ROLE_TO_ASSUME}}", ROLE_TO_ASSUME);
+          gsub("%{{ROLE_DURATION_SECONDS}}", ROLE_DURATION_SECONDS);
+          gsub("%{{ROLE_SESSION_NAME}}", ROLE_SESSION_NAME);
+          gsub("%{{PROFILE_NAME}}", PROFILE_NAME);
+          gsub("%{{SOURCE_PROFILE_NAME}}", SOURCE_PROFILE_NAME);
+          gsub("%{{OIDC_TOKEN_ENV_VAR}}", OIDC_TOKEN_ENV_VAR);
+          print
+      }' "$BEFORE_HOOK_TEMPLATE" > $BEFORE_HOOK
 
-      aws configure set region "${{ params.region }}" --profile ${{ params.profile-name }}
-      aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile ${{ params.profile-name }}
-      aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" --profile ${{ params.profile-name }}
-      aws configure set aws_session_token "$AWS_SESSION_TOKEN" --profile ${{ params.profile-name }}
+      echo "echo 'Removing aws credentials'" > $AFTER_HOOK
+      echo "[ -f ~/.aws/credentials ] && rm ~/.aws/credentials || true" >> $AFTER_HOOK
 
-      unset AWS_ACCESS_KEY_ID
-      unset AWS_SECRET_ACCESS_KEY
-      unset AWS_SESSION_TOKEN
+      chmod +x $BEFORE_HOOK
+      chmod +x $AFTER_HOOK
+
     cache: false
