[mint/install-python] Generate layers without system dependencies; release 1.3.0

diff --git a/mint/install-python/mint-leaf.yml b/mint/install-python/mint-leaf.yml
--- a/mint/install-python/mint-leaf.yml
+++ b/mint/install-python/mint-leaf.yml
@@ -1,5 +1,5 @@
 name: mint/install-python
-version: 1.2.3
+version: 1.3.0
 description: Install Python, a programming language that lets you work quickly and integrate systems more effectively
 source_code_url: https://github.com/rwx-research/mint-leaves/tree/main/mint/install-python
 issue_tracker_url: https://github.com/rwx-research/mint-leaves/issues
@@ -18,9 +18,21 @@ parameters:
 tasks:
   - key: install-python
     run: |
-      set -eou pipefail
+      set -u
+      source "$MINT_LEAF_PATH/mint-utils.sh"
 
-      # ensure we have a python version
+      #
+      # Check OS support
+      #
+      source "$MINT_LEAF_PATH/mint-utils.sh"
+      if ! mint_os_name_in ubuntu; then
+        echo "Unsupported operating system \`$(mint_os_name)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
+        exit 1
+      fi
+
+      #
+      # Ensure we have a python version
+      #
       if [ "$PYTHON_VERSION" = "" ]; then
         cat << EOF > $(mktemp "$MINT_ERRORS/error-XXXX")
       Invalid parameters: \`python-version\` must be set.
@@ -28,13 +40,31 @@ tasks:
         exit 2
       fi
 
+      #
+      # Install system dependencies
+      #
+      os_packages="ca-certificates libexpat1 libsqlite3-0 media-types readline-common tzdata"
+      if mint_os_version_lte 22.04; then
+        os_packages+=" libmpdec3 libreadline8 libssl3"
+      else
+        os_packages+=" libreadline8t64 libssl3t64 openssl"
+      fi
+
+      sudo apt-get update
+      sudo apt-get install --no-upgrade $os_packages
+      sudo apt-get clean
+
+      #
+      # Install Python
+      #
       # Find the prebuilt Python
       echo "Looking for Python $PYTHON_VERSION..."
       escaped_version=$(echo "$PYTHON_VERSION" | sed "s/\./\\\\./g") # 3.2.2 => 3\.2\.2
-      version_line=$(cat $MINT_LEAF_PATH/known-pythons.csv | { grep "^$escaped_version," || test $? = 1; })
+      escaped_os=$(mint_os_name_version | sed "s/\./\\\\./g")
+      version_line=$(cat $MINT_LEAF_PATH/known-rubies.csv | { grep -E "^$escaped_version,[^,]+,[^,]+,$escaped_os,$(mint_arch)$" || test $? = 1; })
       if [[ -z "$version_line" ]]; then
         cat << EOF > $(mktemp "$MINT_ERRORS/error-XXXX")
-      Python $PYTHON_VERSION is not available in this version of [mint/install-python](https://cloud.rwx.com/leaves/mint/install-python).
+      Python $PYTHON_VERSION is not available in this version of [mint/install-python](https://cloud.rwx.com/leaves/mint/install-python) and OS.
       Try upgrading to the most recent version of this leaf. If the Python version is still not available, [file an issue](https://github.com/rwx-research/mint-leaves/issues/new).
       EOF
         exit 3
@@ -67,6 +97,9 @@ tasks:
 
       # Add pip to PATH
       echo "$HOME/.local/bin" >> "$MINT_ENV/PATH"
+
+      # Update dynamic linker cache to pick up the new Python libraries
+      sudo ldconfig
 
       # cleanup
       rm exclude.txt
