Add user error messages when using an unsupported OS.

diff --git a/azure/install-cli/mint-leaf.yml b/azure/install-cli/mint-leaf.yml
--- a/azure/install-cli/mint-leaf.yml
+++ b/azure/install-cli/mint-leaf.yml
@@ -1,5 +1,5 @@
 name: azure/install-cli
-version: 1.0.1
+version: 1.0.2
 description: Install the Azure CLI
 source_code_url: https://github.com/rwx-research/mint-leaves/tree/main/azure/install-cli
 issue_tracker_url: https://github.com/rwx-research/mint-leaves/issues
@@ -10,6 +10,14 @@ parameters:
     default: "latest"
 
 tasks:
+  - key: check_os
+    run: |
+      source "$MINT_LEAF_PATH/mint-utils.sh"
+      if ! mint_os_package_manager_in apt; then
+        echo "Unsupported operating system or package manager \`$(mint_os_package_manager)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
+        exit 1
+      fi
+
   - key: install-cli
     run: |
       # https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions
diff --git a/github/install-cli/mint-leaf.yml b/github/install-cli/mint-leaf.yml
--- a/github/install-cli/mint-leaf.yml
+++ b/github/install-cli/mint-leaf.yml
@@ -1,10 +1,18 @@
 name: github/install-cli
-version: 1.0.1
+version: 1.0.2
 description: Install the GitHub CLI, gh. It is GitHub on the command line.
 source_code_url: https://github.com/rwx-research/mint-leaves/tree/main/github/install-cli
 issue_tracker_url: https://github.com/rwx-research/mint-leaves/issues
 
 tasks:
+  - key: check_os
+    run: |
+      source "$MINT_LEAF_PATH/mint-utils.sh"
+      if ! mint_os_package_manager_in apt; then
+        echo "Unsupported operating system or package manager \`$(mint_os_package_manager)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
+        exit 1
+      fi
+
   - key: install
     run: |
       sudo mkdir -p -m 755 /etc/apt/keyrings
diff --git a/mint/git-clone/mint-leaf.yml b/mint/git-clone/mint-leaf.yml
--- a/mint/git-clone/mint-leaf.yml
+++ b/mint/git-clone/mint-leaf.yml
@@ -1,5 +1,5 @@
 name: mint/git-clone
-version: 1.6.1
+version: 1.6.2
 description: Clone git repositories over ssh or http, with support for Git Large File Storage (LFS)
 source_code_url: https://github.com/rwx-research/mint-leaves/tree/main/mint/git-clone
 issue_tracker_url: https://github.com/rwx-research/mint-leaves/issues
@@ -37,6 +37,14 @@ parameters:
     default: true
 
 tasks:
+  - key: check_os
+    run: |
+      source "$MINT_LEAF_PATH/mint-utils.sh"
+      if ! mint_os_package_manager_in apt; then
+        echo "Unsupported operating system or package manager \`$(mint_os_package_manager)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
+        exit 1
+      fi
+
   - key: setup
     run: |
       sudo install $MINT_LEAF_PATH/bin/git-ssh-command /usr/local/bin
diff --git a/mint/install-erlang/mint-leaf.yml b/mint/install-erlang/mint-leaf.yml
--- a/mint/install-erlang/mint-leaf.yml
+++ b/mint/install-erlang/mint-leaf.yml
@@ -1,5 +1,5 @@
 name: mint/install-erlang
-version: 1.0.2
+version: 1.0.3
 description: Install Erlang, a programming language used to build massively scalable soft real-time systems with requirements on high availability
 source_code_url: https://github.com/rwx-research/mint-leaves/tree/mint/install-erlang
 issue_tracker_url: https://github.com/rwx-research/mint-leaves/issues
@@ -10,13 +10,17 @@ parameters:
     required: true
 
 tasks:
+  - key: check_os
+    run: |
+      source "$MINT_LEAF_PATH/mint-utils.sh"
+      if ! mint_os_package_manager_in apt; then
+        echo "Unsupported operating system or package manager \`$(mint_os_package_manager)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
+        exit 1
+      fi
+
   - key: packages
     run: |
       source "$MINT_LEAF_PATH/mint-utils.sh"
-      if [ "$(mint_os_name)" != "ubuntu" ]; then
-        echo "This leaf currently only supports Ubuntu." > $(mktemp "$MINT_ERRORS/error-XXXX")
-        exit 1
-      fi
 
       if mint_os_version_gte 24.04; then
         ncurses_package="libncurses6"
diff --git a/mint/install-node/mint-leaf.yml b/mint/install-node/mint-leaf.yml
--- a/mint/install-node/mint-leaf.yml
+++ b/mint/install-node/mint-leaf.yml
@@ -1,5 +1,5 @@
 name: mint/install-node
-version: 1.1.0
+version: 1.1.1
 description: Install Node.js, the cross-platform JavaScript runtime environment
 source_code_url: https://github.com/rwx-research/mint-leaves/tree/mint/install-node
 issue_tracker_url: https://github.com/rwx-research/mint-leaves/issues
@@ -13,6 +13,14 @@ parameters:
     required: false
 
 tasks:
+  - key: check_os
+    run: |
+      source "$MINT_LEAF_PATH/mint-utils.sh"
+      if ! mint_os_package_manager_in apt; then
+        echo "Unsupported operating system or package manager \`$(mint_os_package_manager)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
+        exit 1
+      fi
+
   - key: install
     run: $MINT_LEAF_PATH/bin/install-node
     env:
diff --git a/twingate/setup/mint-leaf.yml b/twingate/setup/mint-leaf.yml
--- a/twingate/setup/mint-leaf.yml
+++ b/twingate/setup/mint-leaf.yml
@@ -1,5 +1,5 @@
 name: twingate/setup
-version: 1.0.1
+version: 1.0.2
 description: Install & setup Twingate
 source_code_url: https://github.com/rwx-research/mint-leaves/tree/main/twingate/setup
 issue_tracker_url: https://github.com/rwx-research/mint-leaves/issues
@@ -10,6 +10,14 @@ parameters:
      required: true
 
 tasks:
+  - key: check_os
+    run: |
+      source "$MINT_LEAF_PATH/mint-utils.sh"
+      if ! mint_os_package_manager_in apt; then
+        echo "Unsupported operating system or package manager \`$(mint_os_package_manager)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
+        exit 1
+      fi
+
   - key: install
     run: |
       echo "deb [trusted=yes] https://packages.twingate.com/apt/ /" | sudo tee /etc/apt/sources.list.d/twingate.list
