Suggest the correct URL if running on Github.

diff --git a/mint/git-clone/mint-leaf.yml b/mint/git-clone/mint-leaf.yml
--- a/mint/git-clone/mint-leaf.yml
+++ b/mint/git-clone/mint-leaf.yml
@@ -36,14 +36,42 @@ tasks:
       sudo install $MINT_LEAF_PATH/bin/git-ssh-command /usr/local/bin
       echo "git-ssh-command" >> $MINT_ENV/GIT_SSH_COMMAND
       if [[ -n "$GIT_SSH_KEY" ]]; then
+        httpRegex="https?:\/\/"
+        if [[ "$CHECKOUT_REPOSITORY" =~ $httpRegex ]]; then
+          errorMessage=$(mktemp "$MINT_ERRORS/error-XXXX")
+          cat << EOF > $errorMessage
+      Invalid parameters: \`repository\` points to an HTTP URL, but \`ssh-key\` was set.
+
+      The current value is \`$CHECKOUT_REPOSITORY\`.
+      EOF
+          githubRegex="https?:\/\/github.com\/(.*)\/(.*)\.git"
+          if [[ $CHECKOUT_REPOSITORY =~ $githubRegex ]]; then
+            org="${BASH_REMATCH[1]}"
+            repo="${BASH_REMATCH[2]}"
+
+            truncate -s-1 $errorMessage
+            echo " Perhaps you meant \`git@github.com:$org/$repo.git\`?" >> $errorMessage
+          fi
+          exit 2
+        fi
+
         echo -n "" > $MINT_VALUES/credentials-arg
       else
         if [[ "$CHECKOUT_REPOSITORY" != http* ]]; then
-          cat << EOF > $(mktemp "$MINT_ERRORS/error-XXXX")
+          errorMessage=$(mktemp "$MINT_ERRORS/error-XXXX")
+          cat << EOF > $errorMessage
       Invalid parameters: \`repository\` must point to an HTTP URL if \`ssh-key\` is not set.
 
       The current value is \`$CHECKOUT_REPOSITORY\`.
       EOF
+          githubRegex="git@github.com:(.*)\/(.*).git"
+          if [[ $CHECKOUT_REPOSITORY =~ $githubRegex ]]; then
+            org="${BASH_REMATCH[1]}"
+            repo="${BASH_REMATCH[2]}"
+
+            truncate -s-1 $errorMessage
+            echo " Perhaps you meant \`https://github.com/$org/$repo.git\`?" >> $errorMessage
+          fi
           exit 2
         fi
 
