Add user error messages when using an unsupported OS. (#208)

diff --git a/aws/install-cli/mint-leaf.yml b/aws/install-cli/mint-leaf.yml
--- a/aws/install-cli/mint-leaf.yml
+++ b/aws/install-cli/mint-leaf.yml
@@ -1,5 +1,5 @@
 name: aws/install-cli
-version: 1.0.2
+version: 1.0.3
 description: Install the AWS CLI
 source_code_url: https://github.com/rwx-research/mint-leaves/tree/main/aws/install-cli
 issue_tracker_url: https://github.com/rwx-research/mint-leaves/issues
@@ -13,6 +13,12 @@ tasks:
   - key: install-unzip-if-necessary
     run: |
       if ! command -v unzip &> /dev/null; then
+        source "$MINT_LEAF_PATH/mint-utils.sh"
+        if ! mint_os_package_manager_in apt; then
+          echo "Unsupported operating system or package manager \`$(mint_os_package_manager)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
+          exit 1
+        fi
+
         sudo apt-get update
         sudo apt-get install unzip
         sudo apt-get clean
@@ -21,6 +27,12 @@ tasks:
   - key: install-gpg-if-necessary
     run: |
       if ! command -v gpg &> /dev/null; then
+        source "$MINT_LEAF_PATH/mint-utils.sh"
+        if ! mint_os_package_manager_in apt; then
+          echo "Unsupported operating system or package manager \`$(mint_os_package_manager)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
+          exit 1
+        fi
+
         sudo apt-get update
         sudo apt-get install gnupg
         sudo apt-get clean
diff --git a/google-cloud/install-cli/mint-leaf.yml b/google-cloud/install-cli/mint-leaf.yml
--- a/google-cloud/install-cli/mint-leaf.yml
+++ b/google-cloud/install-cli/mint-leaf.yml
@@ -1,5 +1,5 @@
 name: google-cloud/install-cli
-version: 1.1.1
+version: 1.1.2
 description: Install the Google Cloud SDK CLI
 source_code_url: https://github.com/rwx-research/mint-leaves/tree/main/google-cloud/install-cli
 issue_tracker_url: https://github.com/rwx-research/mint-leaves/issues
@@ -13,7 +13,16 @@ parameters:
     default: ""
 
 tasks:
+  - key: check-os
+    run: |
+      source "$MINT_LEAF_PATH/mint-utils.sh"
+      if [ "$(mint_os_name)" != "ubuntu" ]; then
+        echo "Unsupported operating system \`$(mint_os_name)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
+        exit 1
+      fi
+
   - key: install-cli
+    after: check-os
     run: |
       architecture=""
       case $(uname -m) in
diff --git a/google/install-chrome/mint-leaf.yml b/google/install-chrome/mint-leaf.yml
--- a/google/install-chrome/mint-leaf.yml
+++ b/google/install-chrome/mint-leaf.yml
@@ -1,5 +1,5 @@
 name: google/install-chrome
-version: 2.0.5
+version: 2.0.6
 description: Install Google Chrome, the official web browser from Google
 source_code_url: https://github.com/rwx-research/mint-leaves/tree/main/google/install-chrome
 issue_tracker_url: https://github.com/rwx-research/mint-leaves/issues
@@ -29,7 +29,16 @@ outputs:
   values-from: [install]
 
 tasks:
+  - key: check-os
+    run: |
+      source "$MINT_LEAF_PATH/mint-utils.sh"
+      if ! mint_os_package_manager_in apt; then
+        echo "Unsupported operating system or package manager \`$(mint_os_package_manager)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
+        exit 1
+      fi
+
   - key: resolve-chrome-version
+    after: check-os
     run: |
       chrome=""
 
diff --git a/hashicorp/install-terraform/mint-leaf.yml b/hashicorp/install-terraform/mint-leaf.yml
--- a/hashicorp/install-terraform/mint-leaf.yml
+++ b/hashicorp/install-terraform/mint-leaf.yml
@@ -1,5 +1,5 @@
 name: hashicorp/install-terraform
-version: 1.0.2
+version: 1.0.3
 description: Install the Terraform CLI, a tool for building, changing, and versioning infrastructure safely and efficiently
 source_code_url: https://github.com/rwx-research/mint-leaves/tree/main/hashicorp/install-terraform
 issue_tracker_url: https://github.com/rwx-research/mint-leaves/issues
@@ -10,7 +10,16 @@ parameters:
     default: "latest"
 
 tasks:
+  - key: check-os
+    run: |
+      source "$MINT_LEAF_PATH/mint-utils.sh"
+      if ! mint_os_package_manager_in apt; then
+        echo "Unsupported operating system or package manager \`$(mint_os_package_manager)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
+        exit 1
+      fi
+
   - key: install
+    after: check-os
     run: |
       curl --fail-with-body https://apt.releases.hashicorp.com/gpg | gpg --dearmor > hashicorp-archive-keyring.gpg
       sudo mv hashicorp-archive-keyring.gpg /usr/share/keyrings
