[mint/install-ruby] Generate layers without system dependencies; release 1.2.0 (#210)

diff --git a/mint/install-ruby/mint-leaf.yml b/mint/install-ruby/mint-leaf.yml
--- a/mint/install-ruby/mint-leaf.yml
+++ b/mint/install-ruby/mint-leaf.yml
@@ -1,5 +1,5 @@
 name: mint/install-ruby
-version: 1.1.11
+version: 1.2.0
 description: Install Ruby, a dynamic programming language with a focus on simplicity and productivity
 source_code_url: https://github.com/rwx-research/mint-leaves/tree/main/mint/install-ruby
 issue_tracker_url: https://github.com/rwx-research/mint-leaves/issues
@@ -15,9 +15,20 @@ parameters:
 tasks:
   - key: install-ruby
     run: |
-      set -eou pipefail
+      set -u
 
-      # ensure we have a ruby version
+      #
+      # Check OS support
+      #
+      source "$MINT_LEAF_PATH/mint-utils.sh"
+      if ! mint_os_package_manager_in apt; then
+        echo "Unsupported operating system or package manager \`$(mint_os_package_manager)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
+        exit 1
+      fi
+
+      #
+      # Ensure we have a ruby version
+      #
       if [ "$RUBY_VERSION" = "" ]; then
         if [ "$RUBY_VERSION_FILE" = "" ]; then
           cat << EOF > $(mktemp "$MINT_ERRORS/error-XXXX")
@@ -35,6 +46,37 @@ tasks:
         fi
       fi
 
+      #
+      # Install system packages
+      #
+      tmp_dir=$(mktemp -d)
+
+      sudo apt-get update
+      sudo apt-get install --no-upgrade -y make xz-utils build-essential bison zlib1g-dev libyaml-dev libgdbm-dev libreadline-dev libncurses-dev libffi-dev
+
+      # Rubies before 3.1 require OpenSSL 1.x
+      if [[ "${RUBY_VERSION:0:3}" == "3.0" || "${RUBY_VERSION:0:2}" == "2." ]]; then
+        pushd "$tmp_dir"
+
+        curl -fsSLO http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
+        curl -fsSLO http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1f-1ubuntu2_amd64.deb
+        curl -fsSLO http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/openssl_1.1.1f-1ubuntu2_amd64.deb
+
+        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
+        sudo dpkg -i libssl-dev_1.1.1f-1ubuntu2_amd64.deb
+        sudo dpkg -i openssl_1.1.1f-1ubuntu2_amd64.deb
+        rm -f *.deb
+        popd
+      else
+        sudo apt-get install --no-upgrade -y libssl-dev
+      fi
+
+      rm -rf "$tmp_dir"
+      sudo apt-get clean
+
+      #
+      # Install Ruby
+      #
       # Find the prebuilt Ruby
       echo "Looking for Ruby $RUBY_VERSION..."
       source "$MINT_LEAF_PATH/mint-utils.sh"
