[google/install-chrome] Add support for Ubuntu 24.04; release v2.1.0 (#214)

diff --git a/google/install-chrome/mint-leaf.yml b/google/install-chrome/mint-leaf.yml
--- a/google/install-chrome/mint-leaf.yml
+++ b/google/install-chrome/mint-leaf.yml
@@ -1,5 +1,5 @@
 name: google/install-chrome
-version: 2.0.7
+version: 2.1.0
 description: Install Google Chrome, the official web browser from Google
 source_code_url: https://github.com/rwx-research/mint-leaves/tree/main/google/install-chrome
 issue_tracker_url: https://github.com/rwx-research/mint-leaves/issues
@@ -32,8 +32,8 @@ tasks:
   - key: resolve-chrome-version
     run: |
       source "$MINT_LEAF_PATH/mint-utils.sh"
-      if ! mint_os_package_manager_in apt; then
-        echo "Unsupported operating system or package manager \`$(mint_os_package_manager)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
+      if ! mint_os_name_in ubuntu; then
+        echo "Unsupported operating system \`$(mint_os_name)\`" > "$(mktemp "$MINT_ERRORS/error-XXXX")"
         exit 1
       fi
 
@@ -78,24 +78,34 @@ tasks:
 
   - key: install
     run: |
+      source "$MINT_LEAF_PATH/mint-utils.sh"
+      os_packages=""
+      if mint_os_version_gte 24.04; then
+        os_packages="libasound2t64 libgtk-4-1 libatk-bridge2.0-0t64 libatk1.0-0t64 libatspi2.0-0t64 libcups2t64 libglib2.0-0t64 libgtk-3-0t64"
+      else
+        os_packages="libasound2 libgtk-3-0 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcups2 libglib2.0-0 libgtk-3-0"
+      fi
+
       echo "Installing Chrome system dependencies"
       sudo apt-get update
-      sudo apt-get install \
-        libglib2.0-0 \
-        libgconf-2-4 \
-        libatk1.0-0 \
-        libatk-bridge2.0-0 \
-        libgdk-pixbuf2.0-0 \
-        libgtk-3-0 \
-        libgbm-dev \
-        libnss3-dev \
-        libxss-dev \
-        libasound2 \
-        xvfb \
+
+      sudo apt-get install --no-upgrade $os_packages \
+        ca-certificates \
         fonts-liberation \
-        libu2f-udev \
+        libcairo2 \
+        libcurl4 \
+        libdbus-1-3 \
+        libexpat1 \
+        libgbm1 \
+        libgdk-pixbuf2.0-0 \
+        libnspr4 \
+        libnss3 \
+        libpango-1.0-0 \
+        libudev1 \
+        libvulkan1 \
+        x11-utils \
         xdg-utils \
-        x11-utils
+        xvfb
       sudo apt-get clean
 
       path_additions=""
